apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-files-pvc
  namespace: spark-team-a
  labels:
    app: spark
    storage-type: s3-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-files-sc
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: s3-files
      usage: spark-data
