apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "order-s3files"
  namespace: spark-team-a
  labels:
    app: "order-s3files"
    queue: root.test
spec:
  type: Python
  sparkVersion: "4.0.1"
  pythonVersion: "3"
  mode: cluster
  image: "public.ecr.aws/data-on-eks/spark:4.0.1-scala2.13-java21-python3-r-ubuntu"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "s3a://<S3_BUCKET>/scripts/pyspark-order.py"
  arguments:
    - "file:///mnt/s3-files/order/input/"
    - "file:///mnt/s3-files/order/output/s3-files/"
  sparkConf:
    # AWS SDK V2
    "spark.hadoop.fs.s3a.aws.credentials.provider": "software.amazon.awssdk.auth.credentials.ContainerCredentialsProvider,software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider"
    "spark.hadoop.fs.s3.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.connection.timeout": "1200000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.maximum": "200"
    "spark.hadoop.fs.s3a.fast.upload": "true"
    "spark.hadoop.fs.s3a.readahead.range": "256K"
    "spark.hadoop.fs.s3a.input.fadvise": "random"
    # K8s Pod naming
    "spark.app.name": "order-s3files"
    "spark.kubernetes.driver.pod.name": "order-s3files-driver"
    "spark.kubernetes.executor.podNamePrefix": "order-s3files"
    # Mount S3 Files PVC on driver
    "spark.kubernetes.driver.volumes.persistentVolumeClaim.s3-files-volume.options.claimName": "s3-files-pvc"
    "spark.kubernetes.driver.volumes.persistentVolumeClaim.s3-files-volume.mount.path": "/mnt/s3-files"
    "spark.kubernetes.driver.volumes.persistentVolumeClaim.s3-files-volume.mount.readOnly": "false"
    # Mount S3 Files PVC on executors
    "spark.kubernetes.executor.volumes.persistentVolumeClaim.s3-files-volume.options.claimName": "s3-files-pvc"
    "spark.kubernetes.executor.volumes.persistentVolumeClaim.s3-files-volume.mount.path": "/mnt/s3-files"
    "spark.kubernetes.executor.volumes.persistentVolumeClaim.s3-files-volume.mount.readOnly": "false"
    # Spark Event logs
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://<S3_BUCKET>/spark-event-logs"
    "spark.eventLog.rolling.enabled": "true"
    "spark.eventLog.rolling.maxFileSize": "64m"
    # Expose Spark metrics for Prometheus
    "spark.ui.prometheus.enabled": "true"
    "spark.executor.processTreeMetrics.enabled": "true"
    "spark.metrics.conf.*.sink.prometheusServlet.class": "org.apache.spark.metrics.sink.PrometheusServlet"
    "spark.metrics.conf.driver.sink.prometheusServlet.path": "/metrics/driver/prometheus/"
    "spark.metrics.conf.executor.sink.prometheusServlet.path": "/metrics/executors/prometheus/"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 20
  driver:
    annotations:
      karpenter.sh/do-not-disrupt: "true"
    cores: 2
    memory: "4g"
    memoryOverhead: "2g"
    serviceAccount: spark-team-a
    nodeSelector:
      karpenter.sh/capacity-type: "on-demand"
      NodeGroupType: "SparkComputeGeneral"
  executor:
    annotations:
      karpenter.sh/do-not-disrupt: "true"
    cores: 2
    instances: 4
    memory: "4g"
    memoryOverhead: "2g"
    serviceAccount: spark-team-a
    nodeSelector:
      karpenter.sh/capacity-type: "spot"
      NodeGroupType: "SparkComputeGeneral"
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - order-s3files
          topologyKey: topology.kubernetes.io/zone
