{
 "title": "Trino Cluster JMX",
 "description": "Trino deploy on k8s, collect jmx to monitor cluster",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(trino_execution_QueryManager_RunningQueries,app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Required Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trino_execution_ClusterSizeMonitor_RequiredWorkers{service=\"trino\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "blocked workers (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trino_memory_ClusterMemoryPool_BlockedNodes{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total vCPU Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trino_memory_ClusterMemoryManager_TotalAvailableProcessors{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Distributed Bytes (cluster memory pool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "trino_memory_ClusterMemoryPool_TotalDistributedBytes{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Free Distributed Bytes (cluster memory pool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}-今日"
    },
    {
     "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{service=~\"${cluster}\"} offset 1d",
     "legendFormat": "{{service}}-昨日"
    },
    {
     "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{service=~\"${cluster}\"} offset 7d",
     "legendFormat": "{{service}}-7日前"
    }
   ]
  },
  {
   "title": "Reserved Revocable Distributed Bytes (cluster memory pool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "trino_memory_ClusterMemoryPool_ReservedRevocableDistributedBytes{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Reserved Distributed Bytes (cluster memory pool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "trino_memory_ClusterMemoryPool_ReservedDistributedBytes{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Cluster User Memory Reservation (Running查询使用总和)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}-今日"
    },
    {
     "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{service=~\"${cluster}\"} offset 1d",
     "legendFormat": "{{service}}-昨日"
    },
    {
     "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{service=~\"${cluster}\"} offset 7d",
     "legendFormat": "{{service}}-7日前"
    }
   ]
  },
  {
   "title": "Cluster Total Memory Reservation (Running Queries)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "trino_memory_ClusterMemoryManager_ClusterTotalMemoryReservation{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "查询执行概况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Running Queries (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "trino_execution_QueryManager_RunningQueries{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}-今日"
    }
   ]
  },
  {
   "title": "Queued Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "trino_execution_QueryManager_QueuedQueries{service=~\"${cluster}\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Submitted Per Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{service=~\"$cluster\"}[1m])",
     "legendFormat": "{{service}}-今日"
    }
   ]
  },
  {
   "title": "Total Completed Per Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{service=~\"$cluster\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Failed Per Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{service=~\"$cluster\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of Leaked Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(trino_memory_ClusterMemoryManager_NumberOfLeakedQueries{service=~\"$cluster\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Queries killed with OOM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "increase(trino_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{service=~\"$cluster\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(trino_execution_QueryManager_ConsumedCpuTimeSecs_TotalCount{service=~\"$cluster\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Avg{service=~\"$cluster\"}",
     "legendFormat": "{{service}}-Avg"
    },
    {
     "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Max{service=~\"$cluster\"}",
     "legendFormat": "{{service}}-Max"
    }
   ]
  }
 ]
}