{
 "title": "Serve Dashboard",
 "tags": [ "rayVersion:2.56.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Application",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{}, application)"
    }
   },
   {
    "name": "HTTP_Route",
    "label": "HTTP Route",
    "query": {
     "query": "label_values(ray_serve_num_http_requests_total{}, route)"
    }
   },
   {
    "name": "gRPC_Method",
    "label": "gRPC Service Method",
    "query": {
     "query": "label_values(ray_serve_num_grpc_requests_total{}, method)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(ray_node_network_receive_speed{}, ray_io_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Utilization",
   "type": "graph",
   "description": "Aggregated utilization of all physical resources (CPU, GPU, memory, disk, or etc.) across the cluster. Ignores application variable.",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "avg(ray_node_cpu_utilization{ray_io_cluster=~\"$Cluster\"})",
     "legendFormat": "CPU (physical)"
    },
    {
     "expr": "sum(ray_node_gpus_utilization{ray_io_cluster=~\"$Cluster\"}) / on() (sum(autoscaler_cluster_resources{resource='GPU',ray_io_cluster=~\"$Cluster\"}) or vector(0))",
     "legendFormat": "GPU (physical)"
    },
    {
     "expr": "sum(ray_node_mem_used{ray_io_cluster=~\"$Cluster\"}) / on() (sum(ray_node_mem_total{ray_io_cluster=~\"$Cluster\"})) * 100",
     "legendFormat": "Memory (RAM)"
    },
    {
     "expr": "sum(ray_node_gram_used{ray_io_cluster=~\"$Cluster\"}) / on() (sum(ray_node_gram_available{ray_io_cluster=~\"$Cluster\"}) + sum(ray_node_gram_used{ray_io_cluster=~\"$Cluster\"})) * 100",
     "legendFormat": "GRAM"
    },
    {
     "expr": "sum(ray_object_store_memory{ray_io_cluster=~\"$Cluster\"}) / on() sum(ray_resources{Name=\"object_store_memory\",ray_io_cluster=~\"$Cluster\"}) * 100",
     "legendFormat": "Object Store Memory"
    },
    {
     "expr": "sum(ray_node_disk_usage{ray_io_cluster=~\"$Cluster\"}) / on() (sum(ray_node_disk_free{ray_io_cluster=~\"$Cluster\"}) + sum(ray_node_disk_usage{ray_io_cluster=~\"$Cluster\"})) * 100",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "QPS per application",
   "type": "graph",
   "description": "QPS for each selected application.",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_requests_total{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, route)",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_requests_total{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, method)",
     "legendFormat": "{{application, method}}"
    }
   ]
  },
  {
   "title": "Error QPS per application",
   "type": "graph",
   "description": "Error QPS for each selected application.",
   "gridPos": { "x": 0, "y": 1, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_error_requests_total{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, route)",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_error_requests_total{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, method)",
     "legendFormat": "{{application, method}}"
    }
   ]
  },
  {
   "title": "Error QPS per application per error code",
   "type": "graph",
   "description": "Error QPS for each selected application.",
   "gridPos": { "x": 12, "y": 1, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_error_requests_total{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, route, error_code)",
     "legendFormat": "{{application, route, error_code}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_error_requests_total{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, method, error_code)",
     "legendFormat": "{{application, method, error_code}}"
    }
   ]
  },
  {
   "title": "P50 latency per application",
   "type": "graph",
   "description": "P50 latency for selected applications.",
   "gridPos": { "x": 0, "y": 2, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per application",
   "type": "graph",
   "description": "P90 latency for selected applications.",
   "gridPos": { "x": 8, "y": 2, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket|ray_serve_grpc_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per application",
   "type": "graph",
   "description": "P99 latency for selected applications.",
   "gridPos": { "x": 16, "y": 2, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket|ray_serve_grpc_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Replicas per deployment",
   "type": "graph",
   "description": "Number of replicas per deployment. Ignores \"Application\" variable.",
   "gridPos": { "x": 0, "y": 3, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "replicas" } },
   "yaxes": [
    { "format": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{ray_io_cluster=~\"$Cluster\"}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "QPS per deployment",
   "type": "graph",
   "description": "QPS for each deployment.",
   "gridPos": { "x": 8, "y": 3, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter_total{application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Error QPS per deployment",
   "type": "graph",
   "description": "Error QPS for each deplyoment.",
   "gridPos": { "x": 16, "y": 3, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter_total{application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "P50 latency per deployment",
   "type": "graph",
   "description": "P50 latency per deployment.",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per deployment",
   "type": "graph",
   "description": "P90 latency per deployment.",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per deployment",
   "type": "graph",
   "description": "P99 latency per deployment.",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",ray_io_cluster=~\"$Cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "graph",
   "description": "Number of requests queued per deployment. Ignores \"Application\" variable.",
   "gridPos": { "x": 0, "y": 5, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{ray_io_cluster=~\"$Cluster\"}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "graph",
   "description": "Number of nodes in this cluster. Ignores \"Application\" variable.",
   "gridPos": { "x": 8, "y": 5, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_active_nodes{ray_io_cluster=~\"$Cluster\"}) by (NodeType)",
     "legendFormat": "Active Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_recently_failed_nodes{ray_io_cluster=~\"$Cluster\"}) by (NodeType)",
     "legendFormat": "Failed Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_pending_nodes{ray_io_cluster=~\"$Cluster\"}) by (NodeType)",
     "legendFormat": "Pending Nodes: {{NodeType}}"
    }
   ]
  },
  {
   "title": "Node network",
   "type": "graph",
   "description": "Network speed per node. Ignores \"Application\" variable.",
   "gridPos": { "x": 16, "y": 5, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_network_receive_speed{ray_io_cluster=~\"$Cluster\"}) by (instance)",
     "legendFormat": "Recv: {{instance}}"
    },
    {
     "expr": "sum(ray_node_network_send_speed{ray_io_cluster=~\"$Cluster\"}) by (instance)",
     "legendFormat": "Send: {{instance}}"
    }
   ]
  },
  {
   "title": "Ongoing HTTP Requests",
   "type": "graph",
   "description": "The number of ongoing requests in the HTTP Proxy.",
   "gridPos": { "x": 0, "y": 6, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "ray_serve_num_ongoing_http_requests{ray_io_cluster=~\"$Cluster\"}",
     "legendFormat": "Ongoing HTTP Requests"
    }
   ]
  },
  {
   "title": "Ongoing gRPC Requests",
   "type": "graph",
   "description": "The number of ongoing requests in the gRPC Proxy.",
   "gridPos": { "x": 8, "y": 6, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "ray_serve_num_ongoing_grpc_requests{ray_io_cluster=~\"$Cluster\"}",
     "legendFormat": "Ongoing gRPC Requests"
    }
   ]
  },
  {
   "title": "Scheduling Tasks",
   "type": "graph",
   "description": "The number of request scheduling tasks in the router.",
   "gridPos": { "x": 16, "y": 6, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "ray_serve_num_scheduling_tasks{ray_io_cluster=~\"$Cluster\"}",
     "legendFormat": "Scheduling Tasks"
    }
   ]
  },
  {
   "title": "Scheduling Tasks in Backoff",
   "type": "graph",
   "description": "The number of request scheduling tasks in the router that are undergoing backoff.",
   "gridPos": { "x": 0, "y": 7, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "ray_serve_num_scheduling_tasks_in_backoff{ray_io_cluster=~\"$Cluster\"}",
     "legendFormat": "Scheduling Tasks in Backoff"
    }
   ]
  },
  {
   "title": "Controller Control Loop Duration",
   "type": "graph",
   "description": "The duration of the last control loop.",
   "gridPos": { "x": 8, "y": 7, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "ray_serve_controller_control_loop_duration_s{ray_io_cluster=~\"$Cluster\"}",
     "legendFormat": "Control Loop Duration"
    }
   ]
  },
  {
   "title": "Number of Control Loops",
   "type": "graph",
   "description": "The number of control loops performed by the controller. Increases monotonically over the controller's lifetime.",
   "gridPos": { "x": 16, "y": 7, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "loops" } },
   "yaxes": [
    { "format": "loops" }
   ],
   "targets": [
    {
     "expr": "ray_serve_controller_num_control_loops{ray_io_cluster=~\"$Cluster\"}",
     "legendFormat": "Control Loops"
    }
   ]
  }
 ]
}