# Dockerfile to build a container image for the Gradio app for Mistral-7b model

# Use Python base image
FROM --platform=linux/amd64 python:3.9-slim

# Set working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY gradio-app-mistral.py /app/gradio-app-mistral.py

RUN pip install --no-cache-dir gradio requests

# Command to run the Python script
ENTRYPOINT ["python", "gradio-app-mistral.py"]
