# Use Python base image
FROM --platform=linux/amd64 python:3.9-slim

# Set working directory in the container
WORKDIR /app

# Install necessary Python packages with pinned versions
RUN pip install --no-cache-dir gradio==4.31.5 requests==2.32.2 pillow==10.3.0

# Command to run the Python script
ENTRYPOINT ["python", "/app/gradio-app.py"]
