apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starrocks-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://starrocks.github.io/starrocks-kubernetes-operator
    chart: operator
    targetRevision: "1.11.3"
    helm:
      valuesObject:
        ${user_values_yaml}

  destination:
    server: https://kubernetes.default.svc
    namespace: starrocks

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
