{
 "title": "NVIDIA NIM Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running Pods ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"nim\"})"
    }
   ]
  },
  {
   "title": "Requests Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(num_requests_running{service=\"nim-llm\"})"
    }
   ]
  },
  {
   "title": "Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (histogram_quantile(0.95, rate(time_to_first_token_seconds_bucket{service=\"nim-llm\"}[$__rate_interval])))",
     "legendFormat": "time_to_first_token: {{pod}}"
    },
    {
     "expr": "sum by(pod) (histogram_quantile(0.95, rate(time_per_output_token_seconds_bucket{service=\"nim-llm\"}[$__rate_interval])))",
     "legendFormat": "time_per_output_token: {{pod}}"
    },
    {
     "expr": "sum by(pod) (histogram_quantile(0.95, rate(e2e_request_latency_seconds_bucket{service=\"nim-llm\"}[$__rate_interval])))",
     "legendFormat": "e2e: {{pod}}"
    }
   ]
  },
  {
   "title": "Prompt Tokens Prefill",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(service) (rate(prompt_tokens_total{service=\"nim-llm\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Token generation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(request_prompt_tokens_sum{service=\"nim-llm\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "gpu_cache_usage_perc{service=\"nim-llm\"}",
     "legendFormat": "{{instance}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Max of Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(num_request_max{service=\"nim-llm\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}