{
 "title": "Spark-Operator Scale Test Dashboard",
 "tags": [
  "kubernetes",
  "spark-operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Spark-operator Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (vCPU)",
   "type": "timeseries",
   "description": "CPU used by the spark operator and webhook pods",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(sum by(namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"spark-operator\"}[5m])) * on(namespace, pod) group_left(node) topk by(namespace, pod) (1, max by(namespace, pod, node) (kube_pod_info{node!=\"\"}))) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory working set used by the spark operator and webhook containers ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"spark-operator\"}) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "description": "Bars show the number of items in the work, the red line shows the rate of change in the queue depth per min",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(workqueue_depth{container=\"spark-operator-controller\"}) by (name) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(workqueue_depth{container=\"spark-operator-controller\"}[1m])) by (name) > 0",
     "legendFormat": "1m rate {{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bytes",
   "type": "timeseries",
   "description": "Amount of data transmitted via the network for the spark operator and webhook",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"spark-operator\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive Bytes",
   "type": "timeseries",
   "description": "Amount of data received via the network for the spark operator and webhook",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"spark-operator\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue - Add Rate",
   "type": "timeseries",
   "description": "Rate of additions to the work queue per min",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{container=\"spark-operator-controller\"}[1m])) by (name)  > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue - Work Latency by Percentile",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes, broken down by percentiles 99%, 90%, and 50%",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(workqueue_work_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P99"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(workqueue_work_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P90"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(workqueue_work_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P50"
    }
   ]
  },
  {
   "title": "Work Queue - Queue Latency by Percentile",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested in percentiles 99%, 95%, and 50%",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (name, le)) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P90"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (name, le)) > 0",
     "legendFormat": "{{name}} P50"
    }
   ]
  },
  {
   "title": "Work Queue - Total Retries",
   "type": "timeseries",
   "description": "Total number of retries handled by work queue.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{container=\"spark-operator-controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue - Longest Running Controller Thread",
   "type": "timeseries",
   "description": "How many seconds has the longest running processor for workqueue been running.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{job=\"spark-operator/spark-operator-podmonitor\"}) by (name) > 0",
     "legendFormat": "Longest Running Controller Thread"
    }
   ]
  },
  {
   "title": "Work Queue - Unfinished Work",
   "type": "timeseries",
   "description": "How many seconds of work has been done that is in progress and hasn’t been observed by work_duration. Large values indicate stuck threads.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(workqueue_unfinished_work_seconds{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (name) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Spark Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Start Latency Percentiles",
   "type": "timeseries",
   "description": "Start latency of SparkApplication, broken down by percentiles 99%, 90%, and 50%",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(spark_application_start_latency_seconds_histogram_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (pod,le))",
     "legendFormat": "{{pod}} P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(spark_application_start_latency_seconds_histogram_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (pod,le))",
     "legendFormat": "{{pod}} P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(spark_application_start_latency_seconds_histogram_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (pod,le))",
     "legendFormat": "{{pod}} P50"
    }
   ]
  },
  {
   "title": "Spark Jobs Count",
   "type": "gauge",
   "description": "Counters for spark jobs, these are cumulative over the lifetime of the spark-operator pod",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_count) by (pod)",
     "legendFormat": "Total Spark Jobs Created"
    },
    {
     "expr": "sum(spark_application_failure_count) by (pod)",
     "legendFormat": "Total Failed Spark Jobs"
    },
    {
     "expr": "sum(spark_application_success_count) by (pod)",
     "legendFormat": "Total Successful Spark Jobs"
    },
    {
     "expr": "sum(spark_application_running_count) by (pod)",
     "legendFormat": "Spark Jobs Running"
    },
    {
     "expr": "sum(increase(spark_application_submit_count[5m])) by (pod)",
     "legendFormat": "Jobs Submitted in Last 5min"
    }
   ]
  },
  {
   "title": "Spark Executor Health",
   "type": "piechart",
   "description": "Total number of successful and failed executors",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_success_count)",
     "legendFormat": "Executor Success Count"
    },
    {
     "expr": "sum(spark_executor_failure_count)",
     "legendFormat": "Executor Failure Count"
    }
   ]
  },
  {
   "title": "Spark-submit Rate",
   "type": "timeseries",
   "description": "Total number of SparkApplication spark-submitted by the Operator per min",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(spark_application_submit_count[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Running Rate ",
   "type": "timeseries",
   "description": "Percentage of Spark jobs with Running status out of the total submitted jobs.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spark_application_running_count) / sum(spark_application_submit_count) ",
     "legendFormat": "% of Jobs Running"
    }
   ]
  },
  {
   "title": "Job Success Rate ",
   "type": "timeseries",
   "description": "Percentage of Spark jobs with Success status out of the total submitted jobs.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spark_application_success_count) / sum(spark_application_submit_count) ",
     "legendFormat": "% of Jobs completed Successfully"
    }
   ]
  },
  {
   "title": "Job Failure Rate ",
   "type": "timeseries",
   "description": "Percentage of Spark jobs with Failed status out of the total submitted jobs.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spark_application_failure_count) / sum(spark_application_submit_count) ",
     "legendFormat": "% of Jobs Failed"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "P99 API Server Latency",
   "type": "timeseries",
   "description": "99th percentile of Kubernetes API server latency  summed by API server instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le, instance)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 API Server Latency by Verb",
   "type": "timeseries",
   "description": "99th percentile of Kubernetes API server latency  summed by Verb.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le, verb)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server Request Count",
   "type": "timeseries",
   "description": "Kubernetes API server request counts aggregated by verb and response code. ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{verb!~\"CONNECT|WATCH\"}[5m])) by (verb,code) > 0",
     "legendFormat": "{{verb}}-{{code}}"
    }
   ]
  },
  {
   "title": "P99 Admission Webhook Latency",
   "type": "timeseries",
   "description": "99th percentile of Kubernetes API server Admission Webhook Latency summed by webhook name and action.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket[5m])) by (le, operation, name)) > 0",
     "legendFormat": "{{name}}-{{operation}}"
    }
   ]
  },
  {
   "title": "P99 ETCD Request Latency",
   "type": "timeseries",
   "description": "99th Percentile of request latency between the Kubernetes API servers and etcd",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le)) > 0",
     "legendFormat": "{{operation}} {{type}}"
    }
   ]
  },
  {
   "title": "API Server Total DB Size ",
   "type": "timeseries",
   "description": "Size of the etcd database file physically allocated in bytes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(apiserver_storage_size_bytes)",
     "legendFormat": "ETCD DB Size"
    }
   ]
  },
  {
   "title": "Spark Application Object Count",
   "type": "timeseries",
   "description": "The total number of SparkApplication CRDs in the cluster",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"sparkapplications.sparkoperator.k8s.io\"})",
     "legendFormat": "sparkapplications.sparkoperator.k8s.io"
    }
   ]
  },
  {
   "title": "Pod Object Count",
   "type": "timeseries",
   "description": "The total number of Pods in the cluster",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"pods\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Node Object Count",
   "type": "timeseries",
   "description": "The total number of Nodes in the cluster",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}