{
 "title": "Detailed  Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster Id",
    "query": {
     "query": "label_values(kafka_broker_active_count{instance_id=~\"$cmp_instance_id\", env_id=~\"$cmp_env_id\"},job)"
    }
   },
   {
    "name": "cmp_env_id",
    "label": "CMP Env Id",
    "query": {
     "query": "label_values(kafka_broker_active_count,env_id)"
    }
   },
   {
    "name": "cmp_instance_id",
    "label": "CMP Instance Id",
    "query": {
     "query": "label_values(kafka_broker_active_count{env_id=~\"$cmp_env_id\"},instance_id)"
    }
   },
   {
    "name": "node_id",
    "label": "Node Id",
    "query": {
     "query": "label_values(kafka_server_connection_count{job=\"$cluster_id\"},instance)"
    }
   },
   {
    "name": "request_type",
    "label": "Kafka Request",
    "query": {
     "query": "label_values(kafka_request_count_total,type)"
    }
   },
   {
    "name": "s3stream_request",
    "label": "S3Stream Request",
    "query": {
     "query": "label_values(kafka_stream_operation_latency_count{operation_type=\"S3Stream\"},operation_name)"
    }
   },
   {
    "name": "s3request",
    "label": "S3 Request",
    "query": {
     "query": "label_values(kafka_stream_operation_latency_count{operation_type=\"S3Request\"},operation_name)"
    }
   },
   {
    "name": "active_controller",
    "label": "Active Controller",
    "query": {
     "query": "query_result(kafka_controller_active_count{job=\"$cluster_id\"} > 0)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM CPU Utilization (Old)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_utilization_ratio{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}-sys"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Utilization (Old)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B / $C", "type": "math" }
   ]
  },
  {
   "title": "JVM CPU Utilization (New)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B / $C", "type": "math" }
   ]
  },
  {
   "title": "JVM Heap Memory Utilization (New)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (kafka_stream_buffer_allocated_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#allocated"
    },
    {
     "expr": "sum by(job, instance) (kafka_stream_buffer_used_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#used"
    },
    { "expression": "1 - $A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Allocation Detailed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance, type) (kafka_stream_buffer_allocated_memory_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (kafka_stream_delta_wal_cache_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Delta_WAL_Cache"
    },
    {
     "expr": "sum by(job, instance) (kafka_stream_block_cache_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Block_Cache"
    }
   ]
  },
  { "title": "Kafka Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, job, type) (rate(kafka_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_request_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_request_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"$request_type\"}",
     "legendFormat": "Node-{{instance}}#{{type}}"
    }
   ]
  },
  {
   "title": "IO Thread Idle Ratio",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_io_threads_idle_rate_1m{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Network Thread Idle Ratio",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_network_threads_idle_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Record Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_commit_latency_avg_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Avg"
    },
    {
     "expr": "kafka_server_kraft_commit_latency_max_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Max"
    }
   ]
  },
  {
   "title": "Fetch Limit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_stream_fetch_limiter_permit_num{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}-{{limiter_name}}"
    }
   ]
  },
  { "title": "KRaft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Current Leader",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_current_leader{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_current_epoch{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Quorum"
    },
    {
     "expr": "kafka_server_kraft_log_end_epoch{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Log"
    }
   ]
  },
  {
   "title": "KRaft Endoffset",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_high_watermark{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#HW"
    },
    {
     "expr": "kafka_server_kraft_log_end_offset{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Log"
    }
   ]
  },
  {
   "title": "Append Record Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_append_records_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch Record Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "kafka_server_kraft_fetch_records_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Event Procsssing Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_event_queue_processing_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Avg"
    },
    {
     "expr": "kafka_event_queue_processing_time_50p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#P50"
    },
    {
     "expr": "kafka_event_queue_processing_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#P99"
    }
   ]
  },
  {
   "title": "Controller Event Queue Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(kafka_event_queue_time_milliseconds_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "Node-{{instance}}#Dequeue"
    },
    {
     "expr": "rate(kafka_event_queue_processing_time_milliseconds_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "Node-{{instance}}#Processing"
    }
   ]
  },
  {
   "title": "Controller Event Queueing Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_event_queue_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#Avg"
    },
    {
     "expr": "kafka_event_queue_time_50p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#P50"
    },
    {
     "expr": "kafka_event_queue_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#P99"
    }
   ]
  },
  { "title": "S3Stream Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name, operation_type) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3stream_request\", operation_type=\"S3Stream\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3stream_request\", operation_type=\"S3Stream\"}",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Max Pending Append Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_pending_stream_append_latency_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Max Pending Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_pending_stream_fetch_latency_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_operation_latency_max_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3stream_request\", operation_type=\"S3Stream\"}",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  { "title": "S3 Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3request\", operation_type=\"S3Request\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(operation_name, instance) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Error Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3request\", operation_type=\"S3Request\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_max_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"$s3request\", operation_type=\"S3Request\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  { "title": "Delta WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_wal|append_wal_full\", operation_type=\"S3Storage\", stage=\"complete\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}"
    }
   ]
  },
  {
   "title": "Request Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_max_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}"
    }
   ]
  },
  { "title": "Delta WAL Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache|append_log_cache_full\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "sum by(job, instance, operation_name, status) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Storage\", operation_name=\"read_log_cache\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $C", "type": "math" },
    { "expression": "$B / $E", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name) (kafka_stream_operation_latency_max_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"append_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    },
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_max_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_log_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  { "title": "Upload WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Upload WAL Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"upload_wal|force_upload_wal\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, stage) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"upload_wal|force_upload_wal\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{stage}}"
    }
   ]
  },
  { "title": "Block Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 } },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, instance, operation_name, status) (rate(kafka_stream_operation_latency_count{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=~\"read_block_cache\", operation_type=\"S3Storage\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, status) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_name=\"read_block_cache\", operation_type=\"S3Storage\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Ops Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_stream_block_cache_ops_throughput_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{ops}}"
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 237 } },
  {
   "title": "Total Bytes In / Out",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_network_inbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[1m]))",
     "legendFormat": "Node-{{instance}}#In"
    },
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_network_outbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out"
    }
   ]
  },
  {
   "title": "Total Bytes In / Out (By Priority)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job, type) (rate(kafka_stream_network_inbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In_{{type}}"
    },
    {
     "expr": "sum by(instance, job, type) (rate(kafka_stream_network_outbound_usage_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out_{{type}}"
    }
   ]
  },
  {
   "title": "Total Bytes In / Out (By Type)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_download_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#From_S3"
    },
    {
     "expr": "sum by(instance, job) (rate(kafka_stream_upload_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#To_S3"
    },
    {
     "expr": "sum by(instance, job, direction) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\", direction=\"in\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#In_Msg"
    },
    {
     "expr": "sum by(instance, job, direction) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\", direction=\"out\"}[$__rate_interval])) * -1",
     "legendFormat": "Node-{{instance}}#Out_Msg"
    }
   ]
  },
  {
   "title": "Available Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_stream_network_inbound_available_bandwidth_bytes{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Available Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_stream_network_outbound_available_bandwidth_bytes{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound Network Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_stream_network_inbound_limiter_queue_size{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound Network Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_stream_network_outbound_limiter_queue_size{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Network Inbound Throttle Time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 274 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Network Outbound Throttle Time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 274 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Network Inbound Throttle Time (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, type) (kafka_stream_network_inbound_limiter_queue_time_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#In_{{type}}"
    }
   ]
  },
  {
   "title": "Network Outbound Throttle Time (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, type) (kafka_stream_network_outbound_limiter_queue_time_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#Out_{{type}}"
    }
   ]
  },
  {
   "title": "Network Inbound Throttle Time (Max)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, type) (kafka_stream_network_inbound_limiter_queue_time_max_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#In_{{type}}"
    }
   ]
  },
  {
   "title": "Network Outbound Throttle Time (P99)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, type) (kafka_stream_network_outbound_limiter_queue_time_max_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#In_{{type}}"
    }
   ]
  },
  { "title": "S3 Object", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 310 } },
  {
   "title": "S3 Object Count Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 311 },
   "targets": [
    {
     "expr": "sum by(state) (max by(instance, state) (kafka_stream_s3_object_count{job=\"$cluster_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Object Size vs Msg Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 311 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(job) (kafka_stream_s3_object_size_bytes{job=\"$cluster_id\"})",
     "legendFormat": "S3 Size"
    },
    {
     "expr": "sum(max by(topic, partition) (kafka_log_size{job=\"$cluster_id\"}))",
     "legendFormat": "Msg Size"
    }
   ]
  },
  {
   "title": "StreamSetObject Num",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 323 },
   "targets": [
    {
     "expr": "sum by(node_id) (kafka_stream_stream_set_object_num{job=\"$cluster_id\", node_id=~\"$node_id\"})",
     "legendFormat": "Node-{{node_id}}"
    }
   ]
  },
  {
   "title": "StreamObject Num",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 323 },
   "targets": [
    {
     "expr": "kafka_stream_stream_object_num{job=\"$cluster_id\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Get Object Throughput By Size (Success)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 335 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(size, instance) (rate(kafka_stream_operation_latency_count{operation_type=\"S3Request\", operation_name=\"get_object\", job=\"$cluster_id\", instance=~\"$node_id\", status=\"success\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  {
   "title": "Get Object Request Latency Avg (Success)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 335 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Get Object Request Latency P99 (Success)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 335 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, operation_name, size) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", operation_name=\"get_object\", status=\"success\"})",
     "legendFormat": "Node-{{instance}}#{{operation_name}}-{{size}}"
    }
   ]
  },
  {
   "title": "Upload Object Throughput By Size (Success)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 348 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(size, instance) (rate(kafka_stream_operation_latency_count{operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\", job=\"$cluster_id\", instance=~\"$node_id\", status=\"success\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  {
   "title": "Put Object Request Latency Avg (Success)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 348 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Put Object Request Latency P99 (Success)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 348 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(instance, size) (kafka_stream_operation_latency_99p_nanoseconds{job=\"$cluster_id\", instance=~\"$node_id\", operation_type=\"S3Request\", operation_name=~\"put_object|upload_part\", status=\"success\"})",
     "legendFormat": "Node-{{instance}}#{{size}}"
    }
   ]
  },
  { "title": "Sparse Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 361 } },
  {
   "title": "Stream Num In Local Cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 362 },
   "targets": [
    {
     "expr": "kafka_stream_local_stream_range_index_cache_stream_num{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Local Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 362 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_stream_local_stream_range_index_cache_size_bytes{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 362 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(kafka_stream_node_range_index_cache_operation_count_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "Node-{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Get Object Time Avg",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 373 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Objects To Search Num Avg",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 373 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 384 } },
  {
   "title": "Compaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 385 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_stream_compaction_read_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval])",
     "legendFormat": "Node-{{instance}}#In"
    },
    {
     "expr": "rate(kafka_stream_compaction_write_size_bytes_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]) * -1",
     "legendFormat": "Node-{{instance}}#Out"
    }
   ]
  },
  {
   "title": "Compaction Delay",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 385 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_compaction_delay_time_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  { "title": "Auto-Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 399 } },
  {
   "title": "Metrics Delay",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 400 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_auto_balancer_metrics_time_delay_milliseconds{job=\"$cluster_id\", node_id=~\"$node_id\"}",
     "legendFormat": "Node-{{node_id}}"
    }
   ]
  },
  {
   "title": "Slow Brokers",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 400 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_stream_slow_broker_count{job=\"$cluster_id\", node_id=~\"$node_id\"}",
     "legendFormat": "Node-{{node_id}}"
    }
   ]
  },
  { "title": "Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 414 } },
  {
   "title": "Request Quota Record",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 415 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_broker_quota_value_record{job=\"$cluster_id\", instance=~\"$node_id\", type!=\"Request\"}",
     "legendFormat": "Node-{{instance}} {{type}}"
    },
    {
     "expr": "kafka_broker_quota_value_record{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Request\"}",
     "legendFormat": "Node-{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Request Quota Throttle Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 415 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_broker_quota_throttle_time{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Connection Quota Record",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 429 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_broker_connection_accept_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}} ALL"
    },
    {
     "expr": "kafka_listener_connection_accept_rate{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}} {{listener}}"
    }
   ]
  },
  {
   "title": "Connection Quota Throttle Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 429 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_listener_connection_accept_throttle_time{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}} {{listener}}"
    }
   ]
  }
 ]
}