apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: "0.56.0"
    helm:
      values: |
        ${user_values_yaml}

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
