apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-store
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/awslabs/data-on-eks
    path: infra/terraform/manifests/event-store
    targetRevision: tmp-gitops
    helm:
      valuesObject:
        s3_endpoint: ${clickhouse_s3_endpoint}
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
