{
 "title": "Spark-K8s-Operator-Scale-Test-Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage:",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(sum by(namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"spark-operator\"}[5m])) * on(namespace, pod) group_left(node) topk by(namespace, pod) (1, max by(namespace, pod, node) (kube_pod_info{node!=\"\"}))) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (in GB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"spark-operator\"}) without (container)/1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Webhook Admission Duration",
   "type": "timeseries",
   "description": "Admission Webhook Admission Duration Seconds bucket",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg(rate(apiserver_admission_webhook_admission_duration_seconds_bucket[5m]))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"spark-operator\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server Request Duration (ms)",
   "type": "timeseries",
   "description": "API Server Request Duration(milliseconds)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "avg(rate(apiserver_request_duration_seconds_bucket[5m]))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (in core-seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", namespace=\"spark-operator\" }[5m])) without (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD P99 Latency(seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[5m])) \n  by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server Total DB Size (GB)",
   "type": "timeseries",
   "description": "API Server Total DB Size (in GB)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(apiserver_storage_size_bytes{storage_cluster_id=\"etcd-0\"})/1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 API server latency for all request types",
   "type": "timeseries",
   "description": "P90 API server latency for all request types",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(apiserver_request_duration_seconds_bucket[5m])) \n  by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Spark Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Start Latency Percentiles",
   "type": "timeseries",
   "description": "Start Latency Percentiles",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(spark_application_start_latency_seconds_histogram_bucket{container=\"spark-operator-controller\"}[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(spark_application_start_latency_seconds_histogram_bucket{container=\"spark-operator-controller\"}[5m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Spark Jobs Count",
   "type": "gauge",
   "description": "Spark Jobs (Submitted and Running)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_running_count)",
     "legendFormat": "Total Number of Running Jobs"
    },
    {
     "expr": "sum(increase(spark_application_submit_count[1m]))",
     "legendFormat": "Total Number of Submitted Jobs in last 1 minute"
    }
   ]
  },
  {
   "title": "Spark Executor Health",
   "type": "piechart",
   "description": "Spark Executor Health",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_running_count)",
     "legendFormat": "Executors Running Count"
    },
    {
     "expr": "sum(spark_executor_failure_count)",
     "legendFormat": "Executor Failure Count"
    }
   ]
  },
  {
   "title": "Job Success Rate ",
   "type": "barchart",
   "description": "Spark Job Success Rate Percentage",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "(sum(rate(spark_application_success_count[5m]))) / (sum(rate(spark_application_submit_count[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Failure Rate ",
   "type": "barchart",
   "description": "Spark Job Failure Rate Percentage",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "(sum(rate(spark_application_failure_count[5m]))) / (sum(rate(spark_application_submit_count[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Failure Trend",
   "type": "timeseries",
   "description": "Job Failure Trend",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(spark_application_failure_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WorkQueue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Work Duration P Latency",
   "type": "timeseries",
   "description": "Work Duration P99 and P95 Latency",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{container=\"spark-operator-controller\"}[5m])) by (verb, scope,le)) > 0",
     "legendFormat": "P99 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket{container=\"spark-operator-controller\"}[5m])) by (verb, scope,le)) > 0",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Queue Duration P Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (verb, scope, le)) > 0",
     "legendFormat": "P99 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"spark-operator/spark-operator-podmonitor\"}[5m])) by (le)) > 0",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Unfinished Work",
   "type": "timeseries",
   "description": "Unfinished Work in Seconds",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_unfinished_work_seconds{container=\"spark-operator-controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Longest Running Controller Thread",
   "type": "timeseries",
   "description": "Longest Running Controller Thread",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{container=\"spark-operator-controller\"})/1e6",
     "legendFormat": "Longest Running Controller Thread"
    }
   ]
  },
  {
   "title": "Work Queue Total Adds",
   "type": "barchart",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "rate(workqueue_adds_total{container=\"spark-operator-controller\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue Total Retries",
   "type": "barchart",
   "description": "Work Queue Total Retries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{container=\"spark-operator-controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "description": "Work Queue Depth",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "targets": [
    { "expr": "sum(rate(workqueue_depth[5m]))", "legendFormat": "__auto" }
   ]
  }
 ]
}