{
 "title": "Topic Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster Id",
    "query": {
     "query": "label_values(kafka_broker_active_count{instance_id=~\"$cmp_instance_id\", env_id=~\"$cmp_env_id\"},job)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_log_size{job=\"$cluster_id\"},topic)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(kafka_log_size{topic=\"$topic\", job=\"$cluster_id\"},partition)"
    }
   },
   {
    "name": "cmp_instance_id",
    "label": "CMP Instance Id",
    "query": {
     "query": "label_values(kafka_broker_active_count{env_id=~\"$cmp_env_id\"},instance_id)"
    }
   },
   {
    "name": "cmp_env_id",
    "label": "CMP Env Id",
    "query": {
     "query": "label_values(kafka_broker_active_count,env_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(direction, job) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", topic=\"$topic\", partition=~\"$partition\"}[$__rate_interval]))",
     "legendFormat": "Network-{{direction}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_size{job=\"$cluster_id\", topic=\"$topic\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Topic Partition Count Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(node_id, topic) (kafka_stream_topic_partition_count{job=\"$cluster_id\", topic=\"$topic\"})",
     "legendFormat": "{{topic}}-Node#{{node_id}}"
    }
   ]
  },
  {
   "title": "Topic Partition Count Per Rack",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(rack, topic) (kafka_stream_topic_partition_count{job=\"$cluster_id\", topic=\"$topic\"})",
     "legendFormat": "{{topic}}-Rack#{{rack}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(topic) (max by(topic, partition) (kafka_log_size{job=\"$cluster_id\", topic=\"$topic\"}))",
     "legendFormat": "Partition Count"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (max by(topic, partition) (kafka_log_size{job=\"$cluster_id\", topic=~\"$topic\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_log_size{job=\"$cluster_id\", topic=~\"$topic\", partition=~\"$partition\"}",
     "legendFormat": "{{topic}}-{{partition}}-Node#{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Log End Offset",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_log_end_offset{job=\"$cluster_id\", topic=~\"$topic\", partition=~\"$partition\"}",
     "legendFormat": "{{topic}}-{{partition}}-Node#{{instance}}"
    }
   ]
  },
  {
   "title": "Topic Messages In",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_message_count_total{job=\"$cluster_id\", topic=~\"$topic\", direction=\"in\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(topic) (max by(topic, partition) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", topic=~\"$topic\", direction=\"in\"}[$__rate_interval])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(topic) (max by(topic, partition) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", topic=~\"$topic\", direction=\"out\"}[$__rate_interval])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Produce QPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_request_count_total{job=\"$cluster_id\", topic=~\"$topic\", type=\"produce\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Fetch QPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_request_count_total{job=\"$cluster_id\", topic=~\"$topic\", type=\"fetch\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Partition Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(topic, partition, instance) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", topic=~\"$topic\", direction=\"in\", partition=~\"$partition\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}-{{partition}}-Node#{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(topic, partition, instance) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", topic=~\"$topic\", direction=\"out\", partition=~\"$partition\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}-{{partition}}-Node#{{instance}}"
    }
   ]
  },
  {
   "title": "Consume Statistics",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "max by(topic, partition, consumer_group) (kafka_group_commit_offset{job=\"$cluster_id\", topic=~\"$topic\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(topic, partition) (kafka_log_end_offset{job=\"$cluster_id\", topic=~\"$topic\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}