apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-starrocks
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  iops: "6000"
  throughput: "250"
  encrypted: "true"
  fsType: "xfs"
