---
name: Codespell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Codespell
        uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2.1
        with:
          check_filenames: true
          # When using this Action in other repos, the --skip option below can be removed
          skip: "*.excalidraw,*.git,*.png,*.jpg,*.svg,go.mod,go.sum"
        continue-on-error: true # The PR checks will not fail, but the possible spelling issues will still be reported for review and correction
